apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
spec:
  containers:
  - command: [ "while true", "do date", "sleep $TIME_FREQ", "done" ]
    env:
        # Define the environment variable
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: time-config
              # Specify the key associated with the value
              key: TIME_FREQ
    image: nginx
    name: demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}